from __future__ import annotations

from dataclasses import dataclass


@dataclass(slots=True)
class KnowledgeDocument:
    """
    Structured educational knowledge generated by the Knowledge Agent.
    """

    title: str
    markdown: str